blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView
)

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='article-list'), #path to the blog list page
    path('create/', ArticleCreateView.as_view(), name='article-create'), #path to the blog create page
    path('<int:id>/', ArticleDetailView.as_view(), name='article-detail'), #path to the blog detail page
    path('<int:id>/update/', ArticleUpdateView.as_view(), name='article-update'), #path to the blog update page
    path('<int:id>/delete/', ArticleDeleteView.as_view(), name='article-delete'), #path to the blog delete page
]                                                                                   

storefront/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from pages.views import home_view, contact_view, about_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    #pages urls
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('products/', include('products.urls')), 
    path('blog/',include('blog.urls')),
    path('playground/', include('playground.urls')), 
    path('__debug__/', include(debug_toolbar.urls)) #add this line to the urls.py file to include the debug toolbar urls
    #send all urls that start with playground to the urls.py file in the playground app
]

blog/models.py
from django.db import models
from django.urls import reverse #for redirecting to the article page after creating it

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=120) #max_length required
    content = models.TextField(blank=True,null=True)
    active = models.BooleanField(default=True) #blank - field that is rendereed, null- database

    def get_absolute_url(self):
        return reverse("articles:article-detail", kwargs={"id": self.id})
    

blog/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            'title',
            'content',
            'active'
        ]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import (ListView, DetailView, CreateView, UpdateView, DeleteView) #importing class based views
from .models import Article #import model
from .forms import ArticleForm #import form

## Create your views here.
class ArticleCreateView(CreateView):
    template_name = 'articles/article_create.html' #overide the default template name
    form_class = ArticleForm #form to be used in the view
    queryset = Article.objects.all() 
    #success_url = '/' #redirect to the home page after creating the article
    def form_valid(self,form):
        print(form.cleaned_data)
        return super().form_valid(form)
    
    # def get_sucess_url(self):
    #     return '/'


#simplest class based view, ListView
class ArticleListView(ListView):
    template_name = 'articles/article_list.html' #overide the default template name
    queryset = Article.objects.all() #blog/[modlename]_list.html

#DetailView - class based view for the detail page of the blog
class ArticleDetailView(DetailView):
    template_name = 'articles/article_detail.html' #overide the default template name
    queryset = Article.objects.all() #blog/[modlename]_list.html

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Article, id=id_) #get the object from the url, if not found return 404 error
    

#almost the same as create, but gets an instance of an object and then updates it
class ArticleUpdateView(UpdateView):
    template_name = 'articles/article_create.html' #overide the default template name
    form_class = ArticleForm #form to be used in the view
    queryset = Article.objects.all() 

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Article, id=id_)
    
    def form_valid(self,form):
        print(form.cleaned_data)
        return super().form_valid(form)

#similar to detail view 
class ArticleDeleteView(DeleteView):
    template_name = 'articles/article_delete.html' #overide the default template name

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Article, id=id_) 
    
    def get_success_url(self):
        return reverse('articles:article-list')

blog/templates/articles/article_create.html
{% extends 'base.html'%}

{% block content%}
<h1> Create Article </h1>

<form action ='.' method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save'/>
</form>

{% endblock %}

blog/templates/articles/article_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Article</h1>
    <form action ='.' method ='POST'>  {% csrf_token %}
        <h1>Are you sure you want to delete the article "{{ object.title }}"?</h1>
        <p><input type="submit" value="Yes"/> <a href='../'>Cancel</a> </p>
    </form>
{% endblock %}

blog/templates/articles/article_detail.html
{%extends 'base.html'%}

{% block content %} 
<h1>Article Detail:</h1>
<h1> {{object.title}} </h1>
<p> {{object.content}} </p>
<p> {{object.active}} </p> 

<p><a href="{% url 'articles:article-update' object.id %}">Update</a></p>
<p><a href="{% url 'articles:article-delete' object.id %}">Delete</a></p>
{% endblock %}

blog/templates/articles/article_list.html
{%extends 'base.html'%}
{% block content %} 
<h1>List View Class:</h1>
<h2> This was to test class based views</h2>
<p>ListView, DetailView, CreateView, UpdateView, DeleteView from Django.views.generic</p>
{% if object_list%}
    {% for instance in object_list %}
        <p>{{ instance.id }} -<a href='{{ instance.get_absolute_url}}'> {{ instance.title }}</a></p>
    {% endfor %}
{% else %}
    <h1>Empty</h1>
{% endif %}
<p><a href = "{% url 'articles:article-create' %}">Create</a></p>


{% endblock %}