blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView
)

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='article-list'), #path to the blog list page
    path('create/', ArticleCreateView.as_view(), name='article-create'), #path to the blog create page
    path('<int:id>/', ArticleDetailView.as_view(), name='article-detail'), #path to the blog detail page
    path('<int:id>/update/', ArticleUpdateView.as_view(), name='article-update'), #path to the blog update page
    path('<int:id>/delete/', ArticleDeleteView.as_view(), name='article-delete'), #path to the blog delete page
]                                                                                   

playground/urls.py
#map urls to views
from django.urls import path
from . import views #to reference views

app_name = 'playground'
#url configurations
urlpatterns = [
    path('hello/',views.say_hello,name = "hello"), #this is the url we will use to access this view
]

products/urls.py
from django.urls import path
from .views import(
    product_detail_view, 
    product_create_view,
    product_delete_view,
    product_list_view,
    product_update_view
)
#relative import of all the views in the products app

#namespacing
app_name = 'products'
urlpatterns = [
    path('create/', product_create_view, name='create'),
    path('<int:my_id>/', product_detail_view, name='product-detail'),
    path('<int:my_id>/update', product_update_view, name='product-update'), #update the product
    path('<int:my_id>/delete', product_delete_view, name='product-delete'),
    path('', product_list_view, name='product-list'), #list all products
]

storefront/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from pages.views import home_view, contact_view, about_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    #pages urls
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('products/', include('products.urls')), 
    path('blog/',include('blog.urls')),
    path('playground/', include('playground.urls')), 
    path('__debug__/', include(debug_toolbar.urls)) #add this line to the urls.py file to include the debug toolbar urls
    #send all urls that start with playground to the urls.py file in the playground app
]

templates/about.html
{% extends "base.html"%}

{%block content%}
<h1>About</h1>
<h3>{{ title|capfirst|title}}</h3>
<p>This is a template I created</p>
<p>These values are being access by context I added to a view</p>
{{ my_html|safe }}

<p>
    {{ my_number}}
    {{my_list}}
</p>

<ul>
    <li> Item 1</li>
    <li> Item 2</li>
</ul>
<ul>
{% for item in my_list %}
    <li>{{ forloop.counter }} - {{ item }}</li>
{% endfor %} 
</ul>

{%endblock%}

templates/base.html
<!doctype html>
<html>    
<head>
    <title> Neil Walsh - First Django Project</title>
</head>
<body>
    <h1>Neil Walsh - First Django Project</h1>   
    {% include 'navbar.html' %} 

    {% block content %}
    replace me
    {% endblock %}
</body>
</html>

templates/contact.html
{%extends "base.html" %}


{% block content %}
<h1>Contact</h1>
<p>neilwalsh7788@gmail.com</p>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
    <p>This is the home page</p>
{% endblock %}

templates/navbar.html
<nav>
    <ul> 
        <li> <a href="{% url 'home' %}">Home</a></li>
        <li> <a href="{% url 'about' %}">About</a></li>
        <li> <a href="{% url 'contact' %}">Contact</a></li>
        <li> <a href="{% url 'products:product-list' %}">Products</a></li>
        <li> <a href="{% url 'articles:article-list' %}">Blog</a></li>
        <li> <a href="{% url 'playground:hello' %}">Playground</a></li>
        <li> <a href="{% url 'admin:index' %}">Admin </a></li>
    </ul>
</nav>